version: "3.9"

services:
  client:
    image: neociber/iso810-erp-client
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.client
    container_name: iso810-erp-client
    restart: always
    depends_on:
      - server
    ports:
      - 3000:80
  server:
    image: neociber/iso810-erp-server
    build:
      context: ./backend
      dockerfile: ./Dockerfile.server
    container_name: iso810-erp-server
    depends_on:
      - db
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ISO810_ERP_DB_CONNECTION_STRING=${ISO810_ERP_DB_CONNECTION_STRING}
      - ISO810_JWT_SECRET=${ISO810_JWT_SECRET}
    ports:
      - 5000:5000
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - /iso810-erp/data/mssql/
    container_name: iso810-erp-db
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${ISO810_ERP_SA_PASSWORD}
    ports:
      - 1499:1433
      